// Code generated by "enum -f examples/macro.go -o examples/type_enum.go"; DO NOT EDIT.

package resource

func ResourceTypeEnum() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Video-0]
	_ = x[Audio-1]
	_ = x[Aritcle-2]
}

// ResourceType Key Value Map
var ResourceTypeEnumKeyMap = map[ResourceType]string{
	Video:   "video",
	Audio:   "hahah",
	Aritcle: "article",
}

// ResourceType Value key Map
var ResourceTypeEnumValueMap = map[string]ResourceType{
	"video":   Video,
	"hahah":   Audio,
	"article": Aritcle,
}

func (i ResourceType) String() string {
	return ResourceTypeEnumKeyMap[i]
}

func ResourceTypeByValue(key string) (ResourceType, bool) {
	v, ok := ResourceTypeEnumValueMap[key]
	return v, ok
}
